// src/App.tsx
import { useState } from "react";
import { ConfigProvider, Drawer, message } from "antd";
import zhCN from "antd/locale/zh_CN";
import { invoke } from "@tauri-apps/api";
import MainForm, { FormState } from "./components/MainForm";
import SettingsForm from "./components/SettingsForm";
import FigureZone, { PowerRecords, WorkRecords } from "./components/FigureZone";
import "./App.css";

interface Response {
    p: PowerRecords;
    w: WorkRecords;
}

export default function App() {
    // 侧边栏是否打开
    const [open, setOpen] = useState(false);
    // 图表是否为加载中
    const [spinning, setSpinning] = useState(false);

    const emptyPowerRecords: PowerRecords = {
        eo: { x: [] as string[], y: [] as number[] },
        mp: { x: [] as string[], y: [] as number[] },
        no: { x: [] as string[], y: [] as number[] },
        np: { x: [] as string[], y: [] as number[] },
        er: { x: [] as string[], y: [] as number[] },
        nr: { x: [] as string[], y: [] as number[] },
    };
    const emptyWorkRecords: WorkRecords = {
        m: { x: [] as string[], y: [] as number[] },
        n: { x: [] as string[], y: [] as number[] },
    };

    // 后端处理返回的全部功率、能耗数据
    const [powerRecords, setPowerRecords] = useState<PowerRecords>(emptyPowerRecords);
    const [workRecords, setWorkRecords] = useState<WorkRecords>(emptyWorkRecords);

    const requestFigureData = async (state: FormState) => {
        setPowerRecords(emptyPowerRecords);
        setWorkRecords(emptyWorkRecords);
        setSpinning(true);

        try {
            // @ts-ignore
            const resp: Response = await invoke("build_series", state);

            setPowerRecords(resp.p);
            setWorkRecords(resp.w);
        } catch (e) {
            const msg = `数据处理发生错误：${e as string}`;
            console.error(msg);
            message.error(msg);
        }

        setSpinning(false);
    };

    return (
        <div className='container'>
            <ConfigProvider locale={zhCN}>

                <MainForm
                    onSubmit={requestFigureData}
                    onRequestOpenDrawer={() => setOpen(true)}
                />

                <FigureZone
                    powerRecords={powerRecords}
                    workRecords={workRecords}
                    spinning={spinning}
                />

                <Drawer
                    open={open}
                    onClose={() => { setOpen(false); }}
                    placement='left'
                >
                    <SettingsForm />
                </Drawer>

            </ConfigProvider>
        </div>
    )
}

// src/App.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { invoke } from '@tauri-apps/api';
import { message } from 'ant-design-vue';
import MainForm, { FormState } from './components/MainForm.vue';
import SettingsPage from './components/SettingsPage.vue';
import FigureZone from './components/FigureZone.vue';
import { useSettingsStore } from './stores/settings';
import { storeToRefs } from 'pinia';

interface Response {
  p: unknown[]; // 功率绘图数据
  w: unknown[]; // 能耗绘图数据
}

/** 图表是否为加载中 */
const spinning = ref(false);

/** 侧边栏是否打开，注：不要使用 `open` 作为变量名，会与 tauri-api 中的函数同名 */
const isDrawerOpen = ref(false);

// 后端处理返回的全部功率、能耗数据
const powerRecords = ref<unknown[]>([]);
const workRecords = ref<unknown[]>([]);

const settingsStore = useSettingsStore();
const { smooth, month } = storeToRefs(settingsStore);

// 的经过筛选的数据，用于绘图
const powerData = computed(() => {
  if (powerRecords.value.length === 0) {
    return [];
  }

  if (month.value === 'all') {
    return powerRecords.value;
  }

  return powerRecords.value.filter((r) => (r as any).t.slice(5, 7) === month.value);
});
const workData = computed(() => {
  if (workRecords.value.length === 0) {
    return [];
  }

  if (month.value === 'all') {
    return workRecords.value;
  }

  return workRecords.value.filter((r) => (r as any).d.slice(5, 7) === month.value);
});

// 获取表单数据并发往后端，后端返回绘制图表所需数据，然后利用数据绘图
const requestFigureData = async (state: FormState) => {
  // 清除原有数据，相比直接覆盖显得较为美观
  powerRecords.value = [];
  workRecords.value = [];

  spinning.value = true;

  try {
    const response: Response = await invoke('build_datasets', state as any);
    powerRecords.value = response.p;
    workRecords.value = response.w;
  } catch (e) {
    const msg = `数据处理发生错误：${e as string}`;
    console.error(msg);
    message.error(msg);
  }

  spinning.value = false;
};
</script>

<template>
  <MainForm
    @submit="requestFigureData"
    @requireOpenDrawer="() => isDrawerOpen = true"
  />

  <FigureZone
    :power-data="powerData"
    :work-data="workData"
    :smooth="smooth"
    :spinning="spinning"
  />

  <ADrawer v-model:open="isDrawerOpen" placement="left">
    <SettingsPage />
  </ADrawer>
</template>
